version: "3"
services:
  demo-app:
    build:
      context: .
      dockerfile: .docker/local/Dockerfile
    volumes:
      - .:/app:cached
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=development

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
