"""create_messages_table

Revision ID: 01fff91c9565
Revises: a530f519124f
Create Date: 2025-04-16 05:34:51.566241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01fff91c9565'
down_revision: Union[str, None] = 'a530f519124f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='メッセージID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID'),
    sa.Column('character_id', sa.Integer(), nullable=False, comment='キャラクターID'),
    sa.Column('content', sa.Text(), nullable=False, comment='メッセージ内容'),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False, comment='メッセージの役割(user/assistant)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='作成日時'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
