"""create_user_table

Revision ID: a80e4e71b885
Revises: 
Create Date: 2025-04-15 01:43:57.999374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80e4e71b885'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ユーザーID'),
    sa.Column('line_user_id', sa.VARCHAR(length=255), nullable=False, comment='LINE User ID'),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False, comment='ユーザー名'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='更新日時'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
